export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <div className="flex flex-col min-h-screen">
      {children}
    </div>
  )
}
